### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by Phoscur** [robotlolita/fuck-you#25]
I tested this on my work machine (Macbook) and found it to be working well, but it doesn't on windows.

Could this be supported with node-windows? Or would this be the concern of a new fuck-you-windows module?

**Comment by robotlolita** [comment]
It should work on Windows.

Can you describe what didn't work and the steps to reproduce that problem?

(Note that on Windows, processes are usually named `foo.exe`, so you'd need to run `fuck you foo.exe` or `fuck you foo*` — the wildcard matches anything. See https://github.com/robotlolita/fuck-you/issues/20#issuecomment-133726474 for more details)

**Comment by Phoscur** [comment]
Thanks that actually does work! Please add to readme!
